Added [org.flatland/useful "0.11.5"] as dependency (trying to fix the compilation error "java.lang.IllegalAccessError: groupings does not exist, compiling:(oph/common/util/util.clj:1:1)").